config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "products#index"
  resources :products do
    collection do
      get 'mypage' #マイページ(製作者のみ入れるページ)
      get 'profile' #プロフィール
      get 'skill' #プロフィール
      get 'contact'
      get 'hobby'
      get 'works'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Profile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/contact.html.haml
.contact_wrapper
  .contact_main
    .contact_title
      %h1.contact_main_title
        Contact
    .contact_explanation
      .contact
        .title
          《メールアドレス》
        .contact_mail
          n73.matsuno.kengo[at]gmail.com
      .contact
        .sns_title
          《SNS》
        .sns_text
          %ul.sns_flex{type: "disc"}
            %li
              %a.icon{href: "https://twitter.com/kengo_sr" }
                %span.fa.fa-twitter
                  kengo_sr
            %li
              %a.icon{href: "https://qiita.com/kengo922" }
                %span.fa.fa-search
                  Qiita
            %li
              %a.icon{href: "https://github.com/kengo922"}
                %span.fa.fa-github
                  kengo922
      .contact
        .title
          《問い合わせ》
        .contact_mail
          %a{href: "https://forms.gle/4wt1hRc23kNRmJYj8", class: "inquiry"}
            お問い合わせフォーム
      .contact_back
        = link_to "戻る", root_path ,class: "contact_bottun"

app/views/products/hobby.html.haml
.hobby_wrapper
  .hobby_main
    %h1.hobby_main_title
      Plofile
    .hobby_image_career
      .hobby_image
        = image_tag asset_path("pic0109.png"),class: "hobby_picture", id:"hobby_pictures" ,alt: "nantyan.jpg"
        = image_tag asset_path("skate.jpg"),class: "hobby_picture", id:"hobby_pictures" ,alt: "nantyan.jpg"
      .hobby_career
        .hobby
          .hobby_title
            《趣味》
          .hobby_text1
            %ul{type: "disc"}
              %li ペン回し
              (Japen7th出演 ナランハペン回しフェスティバル 2018年 5位)
              %li スケートボード
        .hobby1
          .hobby_title1
            《ペン回しについて》
          .hobby_text2
            　高校1年生の時に、弟に見せてもらったペン回しの動画を見た際、その凄さに衝撃を受けそこからペン回しを競技として始めました。
            %br/
            　高校生時代は、時間があればずっとペン回しの練習をしていました。その成果もあり、始めて1年後ぐらいで、多くのペン回し動画作品に参加することができました。
            今でも海外からの出演依頼や国内からの出演依頼があるため、多くの作品に出演しております。
            %br/
            　この趣味に出会って10年以上経ちますが、今でもずっと練習をしております。
        .hobby2
          .hobby_title1
            《スケートボードについて》
          .hobby_text2
            　大学生時代、ストリートファッションが好きで、特にスケートボードブランドの服を好んで着ていました。
            %br/
            　スケーターの格好の真似だけではなく、自身もスケボーを上手く乗れるようになりたいと思い、2年程前から始めました。
            始めた当初は滑ること自体が難しく、練習しても上手くならないため、全然練習していませんでした。しかし、1年程前にスケートパークに行った際、リアルなスケーターの滑りを見て、憧れるようになり、そこから本格的に練習を初めした。
            %br/
            　今では、30cm程の高さの障害物を超えたり、物に乗ったりできまでに成長しました。また、板を回したりする技とかもできるようになりました。

    .home_back
      = link_to "戻る", root_path ,class: "bottun"
    .movie_title
      %h2.name_title
        私のフルパートの動画です！
    .movie
      .penspinning_movie
        %iframe{allow: "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", allowfullscreen: "", frameborder: "0", height: "315", src: "https://www.youtube.com/embed/0CqFEDzDkIA", width: "560"}

app/views/products/index.html.haml
.wrapper#section
  .main
    %header.header
      .header__title
        -# = link_to "管理者画面", mypage_products_path , class: "header__title--text"
    .secondary
      .title
        %h1.index_title
          Kengo Matsuno Plofile
      .time
        .view_clock#clock
      %nav.nav
        %ul.wrap
          %li.inline-block
            = link_to "PROFILE", profile_products_path ,class: "word"
          %li.inline-block
            = link_to "SKILL", skill_products_path ,class: "word"
          %li.inline-block
            = link_to "WORKS", works_products_path ,class: "word"
          %li.inline-block
            = link_to "HOBBY", hobby_products_path ,class: "word"
          %li.inline-block
            = link_to "CONTACT", contact_products_path ,class: "word"
    %footer.footer
      .footer__title
        = link_to "2020 製作者：松野健吾" ,'#', class: "footer__title--text"

app/views/products/profile.html.haml
.profile_wrapper
  .profile_main
    .profile_title
      %h1.profile_main_title
        Plofile
    .profile_image_career
      .profile_image
        = image_tag asset_path("img1.jpg"),class: "picture", id:"pictures" ,alt: "nantyan.jpg"
      .profile_career
        .name_title
          .title
            《名前》
          .name
            松野健吾
        .educational_background
          .title
            《学歴》
          .text
            %ul.text_educational
              %li 2015年 3月 大同大学工学部総合機械工学科機械システム専攻 (学士)
              %li 2017年 3月 大同大学大学院工学研究科機械工学専攻 (修士)
        .career
          .title
            《経歴》
          .text
            %ul{type: "disc"}
              %li 大手プラスチック製造会社に入社
              %li 新規素材の技術開発部署で3年勤務
              %li テックキャンプでプログラミングを学び、転職活動中(2020年6月更新）
        .interest
          .title
            《プログラマーを目指す経緯》
          .text#introduction
            服が好きで、アパレルとエンジニアを結び付けた仕事ができたら理想だと思い、
            ITエンジニアであればその両方を兼ね備えた仕事ができるのではないかと考え、プログラミングに興味を持ちました。
            %br/
            　最初は、Progateやpaiza等でrubyの基礎を独学していました。
            次第にアプリの開発やIT業界への転職を本格的に考え始めるようになり、プログラミングについてより深く勉強するため、テックキャンプへ入校することを決めました。

    .profile_home_back
      = link_to "戻る", root_path ,class: "profile_bottun"

app/views/products/skill.html.haml
.skill_wrapper
  .skill_main
    %header.header_skill
      .header_skill_title
    .skill_title
      %h1.skill_main_title
        Skill
    .skill_explanation
      .language
        .skill_language_title
          《プログラミング言語》
        .skill_language_word
          Ruby/Ruby on Rails, Javascript, jQuery, Rspec, Mini test
      .language
        .skill_language_title
          《データーベース》
        .skill_language_word
          MySQL, SQlite
      .language
        .skill_language_title
          《インフラ》
        .skill_language_word
          AWS(EC2、S3等), Heroku, Docker/docker-compose, CircleCI
      .language
        .skill_language_title
          《開発ツール》
        .skill_language_word
          Git hub,Docker hub, Visual Studio Code, AWS Cloud9
      .language
        .skill_language_title
          《現在勉強中の内容》
        .skill_text
          私は現在、多くのIT企業で導入が増えているDockerについて勉強しています。
          現時点では、公式サイトを参考にしながらですがdokcerfile、docker-compose.ymlの記述の仕方やコードの意味を理解する勉強をしています。
          また、開発環境にdockerを導入してアプリ制作なども行っております。
          %br/
          　今後は、本番環境にdockerを適用したり、複数コンテナーを立ち上げるようなdockerfile、docker-compose.ymlの作成ができるようにもっとdockerについて勉強していく予定です。
          %br/
          　アプリ制作に関しては、Railsチュートリアルの復習や自身が触ったことのない機能を作成したりし、railsで開発技術向上を行っております。
          %br/
          今後は、SWiftやGo等のトレンドである技術にも挑戦し、幅広い分野で開発できるエンジニアになりたいと考えています。

    .skill_back
      = link_to "戻る", root_path ,class: "skill_bottun"
    %footer.footer_skill
      .footer_skill_title

app/views/products/works.html.haml
.works_wrapper
  .works_main
    .works_main_title
      %h1.works_main_title
        works
    .all_works
      .works
        .works_title
          《作品タイトル》
        .works_title_name
          ペン回し専用の動画投稿フォーラム Penspinning Videos
        .works_image
          = image_tag asset_path("penspin.png"),class: "works_picture" ,alt: "works"
        .works_url_title
          《URL》
        .works_url
          %a{href: "https://www.kengo-penspinning-app.xyz/", class: "works_word"} https://www.kengo-penspinning-app.xyz/
        .works_note
          URLをクリックするとページに飛べます
        .works_github_title
          《git hub》
        .works_github
          %a{href: "https://github.com/kengo922/penspinning", class: "works_word"} https://github.com/kengo922/penspinning
        .works_note
          URLをクリックするとページに飛べます
        .works_explanationb_title
          《説明》
        .works_explanation#explanation_sub
          ペン回し動画専用の動画共有サイトを作成しました!!

      .works
        .works_title
          《作品タイトル》
        .works_title_name
          自動配色選択コーディネートアプリ Tetrads(テトラード)
        .works_image
          = image_tag asset_path("work1.png"),class: "works_picture" ,alt: "works"
        .works_url_title
          《URL》
        .works_url
          %a{href: "https://kengo-matsuno333.herokuapp.com/", class: "works_word"} https://kengo-matsuno333.herokuapp.com/
        .works_note
          URLをクリックするとページに飛べます
        .works_github_title
          《git hub》
        .works_github
          %a{href: "https://github.com/kengo922/fuku", class: "works_word"} https://github.com/kengo922/fuku
        .works_note
          URLをクリックするとページに飛べます
        .works_explanationb_title
          《説明》
        .works_explanation#explanation_sub
          自身の持っている服の配色を登録する事で、ボタン一つでランダムに配色コーディネートを決定してくれるアプリを作成しました。

      .works
        .works_title
          《作品タイトル》
        .works_title_name
          Railsチュートリアル
        .works_image
          = image_tag asset_path("rails_tutorial.png"),class: "works_picture" ,alt: "works"
        .works_github_title
          《git hub》
        .works_github
          %a{href: "https://github.com/kengo922/sample_app", class: "works_word"} https://github.com/kengo922/sample_app"
        .works_note
          ※ URLのクリックでページに飛べます
        .works_explanationb_title
          《説明》
        .works_explanation#explanation_sub
          ruby on railsの知識をより深く身に着けるため、Railsチュートリアルを行いました。

      .works
        .works_title
          《作品タイトル》
        .works_title_name
          自己紹介サイト
        .works_image
          = image_tag asset_path("profile.png"),class: "works_picture" ,alt: "works"
        .works_github_title
          《git hub》
        .works_github
          %a{href: "https://github.com/kengo922/profile", class: "works_word"} https://github.com/kengo922/profile
        .works_note
          ※ URLをクリックするとページに飛べます
        .works_explanationb_title
          《説明》
        .works_explanation#explanation_sub
          私のことを知って頂くための自己紹介サイトを作成しました！

      .works
        .works_title
          《作品タイトル》
        .works_title_name
          フリマサイト (３人１チームのアジャイル開発で制作)
        .works_image
          = image_tag asset_path("furima_app.png"),class: "works_picture" ,alt: "works"
        .works_url_title
          《URL》
        .works_url
          %a{href: "http://18.178.152.156/", class: "works_word"} http://18.178.152.156/
        .works_note
          ※ URLをクリックするとページに飛べます
        .works_basic_title
          《ベイシック認証》
        .works_pass
          ユーザー名: kengo  ,  パスワード: s72ifea3
        .works_github_title
          《git hub》
        .works_github
          %a{href: "https://github.com/kengo922/free_app", class: "works_word"} https://github.com/kengo922/free_app
        .works_note
          ※ URLをクリックするとページに飛べます
        .works_explanationb_title
          《説明》
        .works_explanation#explanation_sub
          模擬ですがフリーマーケットサイトを作成しました。約1ヶ月間、3人チームでアジャイル開発を行いました。

      .works
        .works_title
          《作品タイトル》
        .works_title_name
          chat-space
        .works_image
          = image_tag asset_path("chat-space.gif"),class: "works_picture" ,alt: "works"
        .works_url_title
          《URL》
        .works_url
          %a{href: "http://3.20.161.142", class: "works_word"} http://3.20.161.142
        .works_note
          ※ URLをクリックするとページに飛べます
        .works_github_title
          《git hub》
        .works_github
          %a{href: "https://github.com/kengo922/chat-space", class: "works_word"} https://github.com/kengo922/chat-space
        .works_note
          ※ URLをクリックするとページに飛べます
        .works_explanationb_title
          《説明》
        .works_explanation#explanation_sub
          非同期、自動更新を組み込んだ、チャットアプリを開発しました。


      .works_back
        = link_to "戻る", root_path ,class: "bottun"

app/views/profiles/index.html.haml
.wrapper#section
  .main
    %header.header
    .secondary 
      .logo
        = image_tag asset_path("kengo_matsuno_plofile1.png"), alt: "icon-02.png",class: "image"
      .time
        .view_clock 
        .view_area 
      %nav.nav
        %ul.wrap
          %li.inline-block
            = link_to "PROFILE", root_path ,class: "word"
          %li.inline-block
            = link_to "SKILL", root_path ,class: "word"
          %li.inline-block
            = link_to "WORKS", root_path ,class: "word"
          %li.inline-block
            = link_to "CONTACT", root_path ,class: "word"
    %footer.footer
      .footer__title
        = link_to "2020 Creator:Kengo Matsuno", '#', class: "footer__title--text"




      -# #social
      -#   %a#facebook{:href => "https://www.facebook.com/supremeofficial", :target => "_blank"}
      -#   %a#instagram{:href => "http://instagram.com/supremenewyork", :target => "_blank"}
      -#   %a#app_store{:href => "https://itunes.apple.com/us/app/supreme/id664573705?mt=8", :target => "_blank"}
  -# #background-image-container
  -#   %img#background-image{"data-image" => "//assets.supremenewyork.com/assets/bg/4-7b9b4f69751409d8e2ac8842ad103f9f.gif", :height => "702", :src => "//assets.supremenewyork.com/assets/bg/4-7b9b4f69751409d8e2ac8842ad103f9f.gif", :style => "opacity: 1; display: block;", :width => "988"}/
  -# %footer#nav{:style => "opacity: 1;"}
  -#   #mobile_nav
  -#     %ul
  -#       %li
  -#         %a{:href => "http://www.supremenewyork.com/news"}
  -#           %span news
  -#       %li
  -#         %a{:href => "/previews/springsummer2020"}
  -#           %span preview
  -#       %li
  -#         %a.lookbook_link{:href => "/lookbooks"}
  -#           %span lookbook
  -#     %ul
  -#       %li
  -#         %a.shop_link{:href => "/shop"}
  -#           %span shop
  -#       %li
  -#         %a.no-right-padding{:href => "/random/tupac"}
  -#           %span random
  -#       %li
  -#         %a{:href => "/stores"}
  -#           %span stores